/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.csstats.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import ru.csdm.stats.common.model.csstats.Csstats;
import ru.csdm.stats.common.model.csstats.Indexes;
import ru.csdm.stats.common.model.csstats.Keys;
import ru.csdm.stats.common.model.csstats.tables.records.PlayerIpRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerIp extends TableImpl<PlayerIpRecord> {

    private static final long serialVersionUID = -695464858;

    /**
     * The reference instance of <code>csstats.player_ip</code>
     */
    public static final PlayerIp PLAYER_IP = new PlayerIp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerIpRecord> getRecordType() {
        return PlayerIpRecord.class;
    }

    /**
     * The column <code>csstats.player_ip.id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>csstats.player_ip.player_id</code>.
     */
    public final TableField<PlayerIpRecord, UInteger> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>csstats.player_ip.ip</code>.
     */
    public final TableField<PlayerIpRecord, String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>csstats.player_ip.reg_datetime</code>.
     */
    public final TableField<PlayerIpRecord, LocalDateTime> REG_DATETIME = createField("reg_datetime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>csstats.player_ip</code> table reference
     */
    public PlayerIp() {
        this(DSL.name("player_ip"), null);
    }

    /**
     * Create an aliased <code>csstats.player_ip</code> table reference
     */
    public PlayerIp(String alias) {
        this(DSL.name(alias), PLAYER_IP);
    }

    /**
     * Create an aliased <code>csstats.player_ip</code> table reference
     */
    public PlayerIp(Name alias) {
        this(alias, PLAYER_IP);
    }

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerIp(Name alias, Table<PlayerIpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PlayerIp(Table<O> child, ForeignKey<O, PlayerIpRecord> key) {
        super(child, key, PLAYER_IP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Csstats.CSSTATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PLAYER_IP_ID_UNIQUE, Indexes.PLAYER_IP_PLAYER_IP_PLAYER_ID_IDX, Indexes.PLAYER_IP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PlayerIpRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PLAYER_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PlayerIpRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_IP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PlayerIpRecord>> getKeys() {
        return Arrays.<UniqueKey<PlayerIpRecord>>asList(Keys.KEY_PLAYER_IP_PRIMARY, Keys.KEY_PLAYER_IP_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PlayerIpRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PlayerIpRecord, ?>>asList(Keys.PLAYER_IP_PLAYER_ID_FK);
    }

    public Player player() {
        return new Player(this, Keys.PLAYER_IP_PLAYER_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerIp as(String alias) {
        return new PlayerIp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerIp as(Name alias) {
        return new PlayerIp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(String name) {
        return new PlayerIp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerIp rename(Name name) {
        return new PlayerIp(name, null);
    }
}
