/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.csstats;


import ru.csdm.stats.common.model.csstats.tables.*;


/**
 * Convenience access to all tables in csstats
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>csstats.history</code>.
     */
    public static final History HISTORY = ru.csdm.stats.common.model.csstats.tables.History.HISTORY;

    /**
     * The table <code>csstats.player</code>.
     */
    public static final Player PLAYER = ru.csdm.stats.common.model.csstats.tables.Player.PLAYER;

    /**
     * The table <code>csstats.player_ip</code>.
     */
    public static final PlayerIp PLAYER_IP = ru.csdm.stats.common.model.csstats.tables.PlayerIp.PLAYER_IP;

    /**
     * The table <code>csstats.player_steamid</code>.
     */
    public static final PlayerSteamid PLAYER_STEAMID = ru.csdm.stats.common.model.csstats.tables.PlayerSteamid.PLAYER_STEAMID;

    /**
     * The table <code>csstats.rank</code>.
     */
    public static final Rank RANK = ru.csdm.stats.common.model.csstats.tables.Rank.RANK;
}
