/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import ru.csdm.stats.common.model.Csstats;
import ru.csdm.stats.common.model.Indexes;
import ru.csdm.stats.common.model.Keys;
import ru.csdm.stats.common.model.tables.records.PlayerSteamidRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerSteamid extends TableImpl<PlayerSteamidRecord> {

    private static final long serialVersionUID = -588383219;

    /**
     * The reference instance of <code>csstats.player_steamid</code>
     */
    public static final PlayerSteamid PLAYER_STEAMID = new PlayerSteamid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerSteamidRecord> getRecordType() {
        return PlayerSteamidRecord.class;
    }

    /**
     * The column <code>csstats.player_steamid.id</code>.
     */
    public final TableField<PlayerSteamidRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>csstats.player_steamid.player_id</code>.
     */
    public final TableField<PlayerSteamidRecord, UInteger> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>csstats.player_steamid.steamid</code>.
     */
    public final TableField<PlayerSteamidRecord, String> STEAMID = createField("steamid", org.jooq.impl.SQLDataType.VARCHAR(22).nullable(false), this, "");

    /**
     * The column <code>csstats.player_steamid.reg_datetime</code>.
     */
    public final TableField<PlayerSteamidRecord, LocalDateTime> REG_DATETIME = createField("reg_datetime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>csstats.player_steamid</code> table reference
     */
    public PlayerSteamid() {
        this(DSL.name("player_steamid"), null);
    }

    /**
     * Create an aliased <code>csstats.player_steamid</code> table reference
     */
    public PlayerSteamid(String alias) {
        this(DSL.name(alias), PLAYER_STEAMID);
    }

    /**
     * Create an aliased <code>csstats.player_steamid</code> table reference
     */
    public PlayerSteamid(Name alias) {
        this(alias, PLAYER_STEAMID);
    }

    private PlayerSteamid(Name alias, Table<PlayerSteamidRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerSteamid(Name alias, Table<PlayerSteamidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PlayerSteamid(Table<O> child, ForeignKey<O, PlayerSteamidRecord> key) {
        super(child, key, PLAYER_STEAMID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Csstats.CSSTATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PLAYER_STEAMID_ID_UNIQUE, Indexes.PLAYER_STEAMID_PLAYER_STEAMID_PLAYER_ID_IDX, Indexes.PLAYER_STEAMID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PlayerSteamidRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PLAYER_STEAMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PlayerSteamidRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_STEAMID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PlayerSteamidRecord>> getKeys() {
        return Arrays.<UniqueKey<PlayerSteamidRecord>>asList(Keys.KEY_PLAYER_STEAMID_PRIMARY, Keys.KEY_PLAYER_STEAMID_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PlayerSteamidRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PlayerSteamidRecord, ?>>asList(Keys.PLAYER_STEAMID_PLAYER_ID_FK);
    }

    public Player player() {
        return new Player(this, Keys.PLAYER_STEAMID_PLAYER_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerSteamid as(String alias) {
        return new PlayerSteamid(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerSteamid as(Name alias) {
        return new PlayerSteamid(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSteamid rename(String name) {
        return new PlayerSteamid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSteamid rename(Name name) {
        return new PlayerSteamid(name, null);
    }
}
