/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.collector;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import ru.csdm.stats.common.model.collector.tables.*;


/**
 * A class modelling indexes of tables of the <code>collector</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DRIVER_PROPERTY_DRIVER_PROPERTY_PROJECT_ID_IDX = Indexes0.DRIVER_PROPERTY_DRIVER_PROPERTY_PROJECT_ID_IDX;
    public static final Index DRIVER_PROPERTY_ID_UNIQUE = Indexes0.DRIVER_PROPERTY_ID_UNIQUE;
    public static final Index DRIVER_PROPERTY_PRIMARY = Indexes0.DRIVER_PROPERTY_PRIMARY;
    public static final Index INSTANCE_ID_UNIQUE = Indexes0.INSTANCE_ID_UNIQUE;
    public static final Index INSTANCE_NAME_UNIQUE = Indexes0.INSTANCE_NAME_UNIQUE;
    public static final Index INSTANCE_PRIMARY = Indexes0.INSTANCE_PRIMARY;
    public static final Index KNOWN_SERVER_ID_UNIQUE = Indexes0.KNOWN_SERVER_ID_UNIQUE;
    public static final Index KNOWN_SERVER_IPPORT_UNIQUE = Indexes0.KNOWN_SERVER_IPPORT_UNIQUE;
    public static final Index KNOWN_SERVER_KNOWN_SERVER_INSTANCE_ID_IDX = Indexes0.KNOWN_SERVER_KNOWN_SERVER_INSTANCE_ID_IDX;
    public static final Index KNOWN_SERVER_KNOWN_SERVER_PROJECT_ID_IDX = Indexes0.KNOWN_SERVER_KNOWN_SERVER_PROJECT_ID_IDX;
    public static final Index KNOWN_SERVER_PRIMARY = Indexes0.KNOWN_SERVER_PRIMARY;
    public static final Index MANAGER_ID_UNIQUE = Indexes0.MANAGER_ID_UNIQUE;
    public static final Index MANAGER_MANAGER_PROJECT_ID_IDX = Indexes0.MANAGER_MANAGER_PROJECT_ID_IDX;
    public static final Index MANAGER_PRIMARY = Indexes0.MANAGER_PRIMARY;
    public static final Index MANAGER_USERNAME_UNIQUE = Indexes0.MANAGER_USERNAME_UNIQUE;
    public static final Index PROJECT_ID_UNIQUE = Indexes0.PROJECT_ID_UNIQUE;
    public static final Index PROJECT_PRIMARY = Indexes0.PROJECT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DRIVER_PROPERTY_DRIVER_PROPERTY_PROJECT_ID_IDX = Internal.createIndex("driver_property_project_id_idx", DriverProperty.DRIVER_PROPERTY, new OrderField[] { DriverProperty.DRIVER_PROPERTY.PROJECT_ID }, false);
        public static Index DRIVER_PROPERTY_ID_UNIQUE = Internal.createIndex("id_UNIQUE", DriverProperty.DRIVER_PROPERTY, new OrderField[] { DriverProperty.DRIVER_PROPERTY.ID }, true);
        public static Index DRIVER_PROPERTY_PRIMARY = Internal.createIndex("PRIMARY", DriverProperty.DRIVER_PROPERTY, new OrderField[] { DriverProperty.DRIVER_PROPERTY.ID }, true);
        public static Index INSTANCE_ID_UNIQUE = Internal.createIndex("id_UNIQUE", Instance.INSTANCE, new OrderField[] { Instance.INSTANCE.ID }, true);
        public static Index INSTANCE_NAME_UNIQUE = Internal.createIndex("name_UNIQUE", Instance.INSTANCE, new OrderField[] { Instance.INSTANCE.NAME }, true);
        public static Index INSTANCE_PRIMARY = Internal.createIndex("PRIMARY", Instance.INSTANCE, new OrderField[] { Instance.INSTANCE.ID }, true);
        public static Index KNOWN_SERVER_ID_UNIQUE = Internal.createIndex("id_UNIQUE", KnownServer.KNOWN_SERVER, new OrderField[] { KnownServer.KNOWN_SERVER.ID }, true);
        public static Index KNOWN_SERVER_IPPORT_UNIQUE = Internal.createIndex("ipport_UNIQUE", KnownServer.KNOWN_SERVER, new OrderField[] { KnownServer.KNOWN_SERVER.IPPORT }, true);
        public static Index KNOWN_SERVER_KNOWN_SERVER_INSTANCE_ID_IDX = Internal.createIndex("known_server_instance_id_idx", KnownServer.KNOWN_SERVER, new OrderField[] { KnownServer.KNOWN_SERVER.INSTANCE_ID }, false);
        public static Index KNOWN_SERVER_KNOWN_SERVER_PROJECT_ID_IDX = Internal.createIndex("known_server_project_id_idx", KnownServer.KNOWN_SERVER, new OrderField[] { KnownServer.KNOWN_SERVER.PROJECT_ID }, false);
        public static Index KNOWN_SERVER_PRIMARY = Internal.createIndex("PRIMARY", KnownServer.KNOWN_SERVER, new OrderField[] { KnownServer.KNOWN_SERVER.ID }, true);
        public static Index MANAGER_ID_UNIQUE = Internal.createIndex("id_UNIQUE", Manager.MANAGER, new OrderField[] { Manager.MANAGER.ID }, true);
        public static Index MANAGER_MANAGER_PROJECT_ID_IDX = Internal.createIndex("manager_project_id_idx", Manager.MANAGER, new OrderField[] { Manager.MANAGER.PROJECT_ID }, false);
        public static Index MANAGER_PRIMARY = Internal.createIndex("PRIMARY", Manager.MANAGER, new OrderField[] { Manager.MANAGER.ID }, true);
        public static Index MANAGER_USERNAME_UNIQUE = Internal.createIndex("username_UNIQUE", Manager.MANAGER, new OrderField[] { Manager.MANAGER.USERNAME }, true);
        public static Index PROJECT_ID_UNIQUE = Internal.createIndex("id_UNIQUE", Project.PROJECT, new OrderField[] { Project.PROJECT.ID }, true);
        public static Index PROJECT_PRIMARY = Internal.createIndex("PRIMARY", Project.PROJECT, new OrderField[] { Project.PROJECT.ID }, true);
    }
}
