/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.collector;


import ru.csdm.stats.common.model.collector.tables.*;


/**
 * Convenience access to all tables in collector
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Additional JDBC driver connection properties https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
     */
    public static final DriverProperty DRIVER_PROPERTY = ru.csdm.stats.common.model.collector.tables.DriverProperty.DRIVER_PROPERTY;

    /**
     * The table <code>collector.instance</code>.
     */
    public static final Instance INSTANCE = ru.csdm.stats.common.model.collector.tables.Instance.INSTANCE;

    /**
     * The table <code>collector.known_server</code>.
     */
    public static final KnownServer KNOWN_SERVER = ru.csdm.stats.common.model.collector.tables.KnownServer.KNOWN_SERVER;

    /**
     * Projects managers
     */
    public static final Manager MANAGER = ru.csdm.stats.common.model.collector.tables.Manager.MANAGER;

    /**
     * The table <code>collector.project</code>.
     */
    public static final Project PROJECT = ru.csdm.stats.common.model.collector.tables.Project.PROJECT;
}
