/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.collector.tables.pojos;


import org.jooq.types.UInteger;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnownServer implements Serializable {

    private static final long serialVersionUID = -1421953127;

    private UInteger id;
    private UInteger projectId;
    private UInteger instanceId;
    private String   ipport;
    private String   name;
    private Boolean  active;
    private Boolean  ffa;
    private Boolean  ignoreBots;
    private Boolean  startSessionOnAction;

    public KnownServer() {}

    public KnownServer(KnownServer value) {
        this.id = value.id;
        this.projectId = value.projectId;
        this.instanceId = value.instanceId;
        this.ipport = value.ipport;
        this.name = value.name;
        this.active = value.active;
        this.ffa = value.ffa;
        this.ignoreBots = value.ignoreBots;
        this.startSessionOnAction = value.startSessionOnAction;
    }

    public KnownServer(
        UInteger id,
        UInteger projectId,
        UInteger instanceId,
        String   ipport,
        String   name,
        Boolean  active,
        Boolean  ffa,
        Boolean  ignoreBots,
        Boolean  startSessionOnAction
    ) {
        this.id = id;
        this.projectId = projectId;
        this.instanceId = instanceId;
        this.ipport = ipport;
        this.name = name;
        this.active = active;
        this.ffa = ffa;
        this.ignoreBots = ignoreBots;
        this.startSessionOnAction = startSessionOnAction;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    public UInteger getProjectId() {
        return this.projectId;
    }

    public void setProjectId(UInteger projectId) {
        this.projectId = projectId;
    }

    @NotNull
    public UInteger getInstanceId() {
        return this.instanceId;
    }

    public void setInstanceId(UInteger instanceId) {
        this.instanceId = instanceId;
    }

    @NotNull
    @Size(max = 21)
    public String getIpport() {
        return this.ipport;
    }

    public void setIpport(String ipport) {
        this.ipport = ipport;
    }

    @NotNull
    @Size(max = 31)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Boolean getFfa() {
        return this.ffa;
    }

    public void setFfa(Boolean ffa) {
        this.ffa = ffa;
    }

    public Boolean getIgnoreBots() {
        return this.ignoreBots;
    }

    public void setIgnoreBots(Boolean ignoreBots) {
        this.ignoreBots = ignoreBots;
    }

    public Boolean getStartSessionOnAction() {
        return this.startSessionOnAction;
    }

    public void setStartSessionOnAction(Boolean startSessionOnAction) {
        this.startSessionOnAction = startSessionOnAction;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final KnownServer other = (KnownServer) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (projectId == null) {
            if (other.projectId != null)
                return false;
        }
        else if (!projectId.equals(other.projectId))
            return false;
        if (instanceId == null) {
            if (other.instanceId != null)
                return false;
        }
        else if (!instanceId.equals(other.instanceId))
            return false;
        if (ipport == null) {
            if (other.ipport != null)
                return false;
        }
        else if (!ipport.equals(other.ipport))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (active == null) {
            if (other.active != null)
                return false;
        }
        else if (!active.equals(other.active))
            return false;
        if (ffa == null) {
            if (other.ffa != null)
                return false;
        }
        else if (!ffa.equals(other.ffa))
            return false;
        if (ignoreBots == null) {
            if (other.ignoreBots != null)
                return false;
        }
        else if (!ignoreBots.equals(other.ignoreBots))
            return false;
        if (startSessionOnAction == null) {
            if (other.startSessionOnAction != null)
                return false;
        }
        else if (!startSessionOnAction.equals(other.startSessionOnAction))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.projectId == null) ? 0 : this.projectId.hashCode());
        result = prime * result + ((this.instanceId == null) ? 0 : this.instanceId.hashCode());
        result = prime * result + ((this.ipport == null) ? 0 : this.ipport.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.ffa == null) ? 0 : this.ffa.hashCode());
        result = prime * result + ((this.ignoreBots == null) ? 0 : this.ignoreBots.hashCode());
        result = prime * result + ((this.startSessionOnAction == null) ? 0 : this.startSessionOnAction.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KnownServer (");

        sb.append(id);
        sb.append(", ").append(projectId);
        sb.append(", ").append(instanceId);
        sb.append(", ").append(ipport);
        sb.append(", ").append(name);
        sb.append(", ").append(active);
        sb.append(", ").append(ffa);
        sb.append(", ").append(ignoreBots);
        sb.append(", ").append(startSessionOnAction);

        sb.append(")");
        return sb.toString();
    }
}
