/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.collector.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import ru.csdm.stats.common.model.collector.tables.Manager;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;


/**
 * Projects managers
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagerRecord extends UpdatableRecordImpl<ManagerRecord> implements Record7<UInteger, UInteger, String, String, Boolean, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1374243142;

    /**
     * Setter for <code>collector.manager.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>collector.manager.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>collector.manager.project_id</code>.
     */
    public void setProjectId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>collector.manager.project_id</code>.
     */
    public UInteger getProjectId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>collector.manager.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>collector.manager.username</code>.
     */
    @NotNull
    @Size(max = 31)
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>collector.manager.password</code>. https://www.browserling.com/tools/bcrypt
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>collector.manager.password</code>. https://www.browserling.com/tools/bcrypt
     */
    @NotNull
    @Size(max = 60)
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>collector.manager.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>collector.manager.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>collector.manager.manage_hosting</code>. 1-can manage all projects in hosting, 0-can manage only project by `project_id`
     */
    public void setManageHosting(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>collector.manager.manage_hosting</code>. 1-can manage all projects in hosting, 0-can manage only project by `project_id`
     */
    public Boolean getManageHosting() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>collector.manager.reg_datetime</code>.
     */
    public void setRegDatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>collector.manager.reg_datetime</code>.
     */
    public LocalDateTime getRegDatetime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, String, String, Boolean, Boolean, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, String, String, Boolean, Boolean, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Manager.MANAGER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Manager.MANAGER.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Manager.MANAGER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Manager.MANAGER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Manager.MANAGER.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Manager.MANAGER.MANAGE_HOSTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Manager.MANAGER.REG_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getManageHosting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getRegDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getManageHosting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getRegDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value2(UInteger value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value6(Boolean value) {
        setManageHosting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord value7(LocalDateTime value) {
        setRegDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagerRecord values(UInteger value1, UInteger value2, String value3, String value4, Boolean value5, Boolean value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagerRecord
     */
    public ManagerRecord() {
        super(Manager.MANAGER);
    }

    /**
     * Create a detached, initialised ManagerRecord
     */
    public ManagerRecord(UInteger id, UInteger projectId, String username, String password, Boolean active, Boolean manageHosting, LocalDateTime regDatetime) {
        super(Manager.MANAGER);

        set(0, id);
        set(1, projectId);
        set(2, username);
        set(3, password);
        set(4, active);
        set(5, manageHosting);
        set(6, regDatetime);
    }
}
