/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;
import ru.csdm.stats.common.model.Csstats;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuildHumanTime extends AbstractRoutine<String> {

    private static final long serialVersionUID = -180232563;

    /**
     * The parameter <code>csstats.build_human_time.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(31), false, false);

    /**
     * The parameter <code>csstats.build_human_time.time_secs</code>.
     */
    public static final Parameter<UInteger> TIME_SECS = Internal.createParameter("time_secs", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * Create a new routine call instance
     */
    public BuildHumanTime() {
        super("build_human_time", Csstats.CSSTATS, org.jooq.impl.SQLDataType.VARCHAR(31));

        setReturnParameter(RETURN_VALUE);
        addInParameter(TIME_SECS);
    }

    /**
     * Set the <code>time_secs</code> parameter IN value to the routine
     */
    public void setTimeSecs(UInteger value) {
        setValue(TIME_SECS, value);
    }

    /**
     * Set the <code>time_secs</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTimeSecs(Field<UInteger> field) {
        setField(TIME_SECS, field);
    }
}
