/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.csstats.tables.pojos;


import org.jooq.types.UInteger;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerSteamid implements Serializable {

    private static final long serialVersionUID = 962297351;

    private UInteger      id;
    private UInteger      playerId;
    private String        steamid;
    private LocalDateTime regDatetime;

    public PlayerSteamid() {}

    public PlayerSteamid(PlayerSteamid value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.steamid = value.steamid;
        this.regDatetime = value.regDatetime;
    }

    public PlayerSteamid(
        UInteger      id,
        UInteger      playerId,
        String        steamid,
        LocalDateTime regDatetime
    ) {
        this.id = id;
        this.playerId = playerId;
        this.steamid = steamid;
        this.regDatetime = regDatetime;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    public UInteger getPlayerId() {
        return this.playerId;
    }

    public void setPlayerId(UInteger playerId) {
        this.playerId = playerId;
    }

    @NotNull
    @Size(max = 22)
    public String getSteamid() {
        return this.steamid;
    }

    public void setSteamid(String steamid) {
        this.steamid = steamid;
    }

    public LocalDateTime getRegDatetime() {
        return this.regDatetime;
    }

    public void setRegDatetime(LocalDateTime regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlayerSteamid other = (PlayerSteamid) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (playerId == null) {
            if (other.playerId != null)
                return false;
        }
        else if (!playerId.equals(other.playerId))
            return false;
        if (steamid == null) {
            if (other.steamid != null)
                return false;
        }
        else if (!steamid.equals(other.steamid))
            return false;
        if (regDatetime == null) {
            if (other.regDatetime != null)
                return false;
        }
        else if (!regDatetime.equals(other.regDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerId == null) ? 0 : this.playerId.hashCode());
        result = prime * result + ((this.steamid == null) ? 0 : this.steamid.hashCode());
        result = prime * result + ((this.regDatetime == null) ? 0 : this.regDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerSteamid (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(steamid);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
