/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model.csstats.tables.pojos;


import org.jooq.types.UInteger;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerIp implements Serializable {

    private static final long serialVersionUID = 389077873;

    private UInteger      id;
    private UInteger      playerId;
    private String        ip;
    private LocalDateTime regDatetime;

    public PlayerIp() {}

    public PlayerIp(PlayerIp value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.ip = value.ip;
        this.regDatetime = value.regDatetime;
    }

    public PlayerIp(
        UInteger      id,
        UInteger      playerId,
        String        ip,
        LocalDateTime regDatetime
    ) {
        this.id = id;
        this.playerId = playerId;
        this.ip = ip;
        this.regDatetime = regDatetime;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    public UInteger getPlayerId() {
        return this.playerId;
    }

    public void setPlayerId(UInteger playerId) {
        this.playerId = playerId;
    }

    @NotNull
    @Size(max = 15)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public LocalDateTime getRegDatetime() {
        return this.regDatetime;
    }

    public void setRegDatetime(LocalDateTime regDatetime) {
        this.regDatetime = regDatetime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlayerIp other = (PlayerIp) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (playerId == null) {
            if (other.playerId != null)
                return false;
        }
        else if (!playerId.equals(other.playerId))
            return false;
        if (ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!ip.equals(other.ip))
            return false;
        if (regDatetime == null) {
            if (other.regDatetime != null)
                return false;
        }
        else if (!regDatetime.equals(other.regDatetime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerId == null) ? 0 : this.playerId.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        result = prime * result + ((this.regDatetime == null) ? 0 : this.regDatetime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerIp (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(ip);
        sb.append(", ").append(regDatetime);

        sb.append(")");
        return sb.toString();
    }
}
