/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.csdm.stats.common.model.tables.History;
import ru.csdm.stats.common.model.tables.KnownServer;
import ru.csdm.stats.common.model.tables.Player;
import ru.csdm.stats.common.model.tables.PlayerIp;
import ru.csdm.stats.common.model.tables.PlayerSteamid;
import ru.csdm.stats.common.model.tables.Rank;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Csstats extends SchemaImpl {

    private static final long serialVersionUID = 699313646;

    /**
     * The reference instance of <code>csstats</code>
     */
    public static final Csstats CSSTATS = new Csstats();

    /**
     * The table <code>csstats.history</code>.
     */
    public final History HISTORY = ru.csdm.stats.common.model.tables.History.HISTORY;

    /**
     * The table <code>csstats.known_server</code>.
     */
    public final KnownServer KNOWN_SERVER = ru.csdm.stats.common.model.tables.KnownServer.KNOWN_SERVER;

    /**
     * The table <code>csstats.player</code>.
     */
    public final Player PLAYER = ru.csdm.stats.common.model.tables.Player.PLAYER;

    /**
     * The table <code>csstats.player_ip</code>.
     */
    public final PlayerIp PLAYER_IP = ru.csdm.stats.common.model.tables.PlayerIp.PLAYER_IP;

    /**
     * The table <code>csstats.player_steamid</code>.
     */
    public final PlayerSteamid PLAYER_STEAMID = ru.csdm.stats.common.model.tables.PlayerSteamid.PLAYER_STEAMID;

    /**
     * The table <code>csstats.rank</code>.
     */
    public final Rank RANK = ru.csdm.stats.common.model.tables.Rank.RANK;

    /**
     * No further instances allowed
     */
    private Csstats() {
        super("csstats", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            History.HISTORY,
            KnownServer.KNOWN_SERVER,
            Player.PLAYER,
            PlayerIp.PLAYER_IP,
            PlayerSteamid.PLAYER_STEAMID,
            Rank.RANK);
    }
}
