/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model;


import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;
import ru.csdm.stats.common.model.collector.Collector;
import ru.csdm.stats.common.model.csstats.Csstats;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -75163028;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>csstats</code>.
     */
    public final Csstats CSSTATS = ru.csdm.stats.common.model.csstats.Csstats.CSSTATS;

    /**
     * The schema <code>collector</code>.
     */
    public final Collector COLLECTOR = ru.csdm.stats.common.model.collector.Collector.COLLECTOR;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            Csstats.CSSTATS,
            Collector.COLLECTOR);
    }
}
