/*
 * This file is generated by jOOQ.
 */
package ru.csdm.stats.common.model;


import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.types.UInteger;
import ru.csdm.stats.common.model.routines.*;


/**
 * Convenience access to all stored procedures and functions in csstats
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>csstats.build_human_time</code>
     */
    public static String buildHumanTime(Configuration configuration, UInteger timeSecs) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.build_human_time</code> as a field.
     */
    public static Field<String> buildHumanTime(UInteger timeSecs) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);

        return f.asField();
    }

    /**
     * Get <code>csstats.build_human_time</code> as a field.
     */
    public static Field<String> buildHumanTime(Field<UInteger> timeSecs) {
        BuildHumanTime f = new BuildHumanTime();
        f.setTimeSecs(timeSecs);

        return f.asField();
    }

    /**
     * Call <code>csstats.build_stars</code>
     */
    public static String buildStars(Configuration configuration, UInteger level, UInteger ranksTotal) {
        BuildStars f = new BuildStars();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.build_stars</code> as a field.
     */
    public static Field<String> buildStars(UInteger level, UInteger ranksTotal) {
        BuildStars f = new BuildStars();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Get <code>csstats.build_stars</code> as a field.
     */
    public static Field<String> buildStars(Field<UInteger> level, Field<UInteger> ranksTotal) {
        BuildStars f = new BuildStars();
        f.setLevel(level);
        f.setRanksTotal(ranksTotal);

        return f.asField();
    }

    /**
     * Call <code>csstats.calculate_rank_id</code>
     */
    public static UInteger calculateRankId(Configuration configuration, UInteger kills, UInteger deaths, UInteger timeSecs) {
        CalculateRankId f = new CalculateRankId();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.calculate_rank_id</code> as a field.
     */
    public static Field<UInteger> calculateRankId(UInteger kills, UInteger deaths, UInteger timeSecs) {
        CalculateRankId f = new CalculateRankId();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);

        return f.asField();
    }

    /**
     * Get <code>csstats.calculate_rank_id</code> as a field.
     */
    public static Field<UInteger> calculateRankId(Field<UInteger> kills, Field<UInteger> deaths, Field<UInteger> timeSecs) {
        CalculateRankId f = new CalculateRankId();
        f.setKills(kills);
        f.setDeaths(deaths);
        f.setTimeSecs(timeSecs);

        return f.asField();
    }

    /**
     * Call <code>csstats.calculate_skill</code>
     */
    public static Integer calculateSkill(Configuration configuration, Long kills, Long deaths) {
        CalculateSkill f = new CalculateSkill();
        f.setKills(kills);
        f.setDeaths(deaths);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.calculate_skill</code> as a field.
     */
    public static Field<Integer> calculateSkill(Long kills, Long deaths) {
        CalculateSkill f = new CalculateSkill();
        f.setKills(kills);
        f.setDeaths(deaths);

        return f.asField();
    }

    /**
     * Get <code>csstats.calculate_skill</code> as a field.
     */
    public static Field<Integer> calculateSkill(Field<Long> kills, Field<Long> deaths) {
        CalculateSkill f = new CalculateSkill();
        f.setKills(kills);
        f.setDeaths(deaths);

        return f.asField();
    }

    /**
     * Call <code>csstats.declension</code>
     */
    public static String declension(Configuration configuration, Integer value, String opt1, String opt2, String opt3) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.declension</code> as a field.
     */
    public static Field<String> declension(Integer value, String opt1, String opt2, String opt3) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        return f.asField();
    }

    /**
     * Get <code>csstats.declension</code> as a field.
     */
    public static Field<String> declension(Field<Integer> value, Field<String> opt1, Field<String> opt2, Field<String> opt3) {
        Declension f = new Declension();
        f.setValue(value);
        f.setOpt1(opt1);
        f.setOpt2(opt2);
        f.setOpt3(opt3);

        return f.asField();
    }

    /**
     * Call <code>csstats.is_valid_ip</code>
     */
    public static Boolean isValidIp(Configuration configuration, String ip, Byte nullable, Byte withPort) {
        IsValidIp f = new IsValidIp();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.is_valid_ip</code> as a field.
     */
    public static Field<Boolean> isValidIp(String ip, Byte nullable, Byte withPort) {
        IsValidIp f = new IsValidIp();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        return f.asField();
    }

    /**
     * Get <code>csstats.is_valid_ip</code> as a field.
     */
    public static Field<Boolean> isValidIp(Field<String> ip, Field<Byte> nullable, Field<Byte> withPort) {
        IsValidIp f = new IsValidIp();
        f.setIp(ip);
        f.setNullable(nullable);
        f.setWithPort(withPort);

        return f.asField();
    }

    /**
     * Call <code>csstats.is_valid_steamid</code>
     */
    public static Boolean isValidSteamid(Configuration configuration, String steamid, Byte nullable, Byte onlyLegal) {
        IsValidSteamid f = new IsValidSteamid();
        f.setSteamid(steamid);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>csstats.is_valid_steamid</code> as a field.
     */
    public static Field<Boolean> isValidSteamid(String steamid, Byte nullable, Byte onlyLegal) {
        IsValidSteamid f = new IsValidSteamid();
        f.setSteamid(steamid);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        return f.asField();
    }

    /**
     * Get <code>csstats.is_valid_steamid</code> as a field.
     */
    public static Field<Boolean> isValidSteamid(Field<String> steamid, Field<Byte> nullable, Field<Byte> onlyLegal) {
        IsValidSteamid f = new IsValidSteamid();
        f.setSteamid(steamid);
        f.setNullable(nullable);
        f.setOnlyLegal(onlyLegal);

        return f.asField();
    }

    /**
     * Call <code>csstats.PlayerDetail</code>
     */
    public static void playerdetail(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerdetail p = new Playerdetail();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerDetailJson</code>
     */
    public static void playerdetailjson(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerdetailjson p = new Playerdetailjson();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerDetailJsonAgg</code>
     */
    public static void playerdetailjsonagg(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerdetailjsonagg p = new Playerdetailjsonagg();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFull</code>
     */
    public static void playerfull(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfull p = new Playerfull();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFull2</code>
     */
    public static void playerfull2(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfull2 p = new Playerfull2();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFull2Json</code>
     */
    public static void playerfull2json(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfull2json p = new Playerfull2json();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFull2JsonAgg</code>
     */
    public static void playerfull2jsonagg(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfull2jsonagg p = new Playerfull2jsonagg();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFullJson</code>
     */
    public static void playerfulljson(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfulljson p = new Playerfulljson();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerFullJsonAgg</code>
     */
    public static void playerfulljsonagg(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playerfulljsonagg p = new Playerfulljsonagg();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerHistoryJsonAgg</code>
     */
    public static void playerhistoryjsonagg(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage, UInteger historyLimit) {
        Playerhistoryjsonagg p = new Playerhistoryjsonagg();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);
        p.setHistoryLimit(historyLimit);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerSummary</code>
     */
    public static void playersummary(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playersummary p = new Playersummary();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerSummaryJson</code>
     */
    public static void playersummaryjson(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playersummaryjson p = new Playersummaryjson();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }

    /**
     * Call <code>csstats.PlayerSummaryJsonAgg</code>
     */
    public static void playersummaryjsonagg(Configuration configuration, UInteger id, String name, String ip, String steamid, UInteger page, UInteger perPage) {
        Playersummaryjsonagg p = new Playersummaryjsonagg();
        p.setId(id);
        p.setName_(name);
        p.setIp(ip);
        p.setSteamid(steamid);
        p.setPage(page);
        p.setPerPage(perPage);

        p.execute(configuration);
    }
}
